### ISSUE TITLE
Cannot read property 'runtimeId' of undefined

### ISSUE THREAD

**Issue by simba909** [koush/electron-chrome#10]
Trying to run electron-chrome with Vysor (using the `--app-id` flag) results in the following startup log for me:

```
using chrome runtime 1.0.7
embedded null found
app not installed, fetching...
App threw an error during load
TypeError: Cannot read property 'runtimeId' of undefined
    at /Users/simon/Documents/personal/electron-chrome/chrome/main/start.js:123:52
    at Object.<anonymous> (/Users/simon/Documents/personal/electron-chrome/chrome/main/start.js:225:3)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.exports.start (/Users/simon/Documents/personal/electron-chrome/chrome/index.js:36:5)
```

The app can't start since Electron gets stuck with the error message in a popup.

Environment:
Node: 6.5.0
Electron: 1.3.5

What could I be doing wrong?

**Comment by koush** [comment]
oh, will fix.
